name: b_finetune_dec
data:
    target: src.dataset.OxfordPet
    params:
        root: "./data/oxford-iiit-pet"
        split_ratio: [0.5, 0.25, 0.25]
model:
    target: src.models.Classifier
    params:
        enc_name: ResNet50
        drop_out: 0.5
        use_batch_norm: True
        head_inters: []
loss:
    target: src.costs.CrossEntropyLoss
optimizer:
    target: torch.optim.AdamW
    params:
        lr: 1.0e-3
        betas: [0.9, 0.999]
        weight_decay: 1.0e-5
lr_scheduler:
    target: torch.optim.lr_scheduler.CosineAnnealingLR
    params:
        T_max: 20
        eta_min: 3.0e-8
train:
    tollerance: 1
    loader_params:
        batch_size: 16
        shuffle: True
val:
    loader_params:
        batch_size: 16
test:
    loader_params:
        batch_size: 16
    visualizer_params:
        grid_size: 6
        max_fig_count: 5
epochs: 100
